package dataframe

import (
	"fmt"

	"go.starlark.net/starlark"
)

type seriesAttrImpl func(*Series) (starlark.Value, error)

var seriesAttributes = map[string]seriesAttrImpl{
	"T":                       attrNoImplSeries("T"),
	"array":                   attrNoImplSeries("array"),
	"at":                      attrNoImplSeries("at"),
	"attrs":                   attrNoImplSeries("attrs"),
	"axes":                    attrNoImplSeries("axes"),
	"dtype":                   attrNoImplSeries("dtype"),
	"dtypes":                  attrNoImplSeries("dtypes"),
	"flags":                   attrNoImplSeries("flags"),
	"hasnans":                 attrNoImplSeries("hasnans"),
	"iat":                     attrNoImplSeries("iat"),
	"iloc":                    attrNoImplSeries("iloc"),
	"index":                   attrNoImplSeries("index"),
	"is_monotonic":            attrNoImplSeries("is_monotonic"),
	"is_monotonic_decreasing": attrNoImplSeries("is_monotonic_decreasing"),
	"is_monotonic_increasing": attrNoImplSeries("is_monotonic_increasing"),
	"is_unique":               attrNoImplSeries("is_unique"),
	"loc":                     attrNoImplSeries("loc"),
	"name":                    seriesAttrName,
	"nbytes":                  attrNoImplSeries("nbytes"),
	"ndim":                    attrNoImplSeries("ndim"),
	"shape":                   attrNoImplSeries("shape"),
	"size":                    seriesAttrSize,
	"values":                  attrNoImplSeries("values"),
}

var seriesMethods = map[string]*starlark.Builtin{
	"abs":               starlark.NewBuiltin("abs", methNoImplSeries("abs")),
	"add":               starlark.NewBuiltin("add", methNoImplSeries("add")),
	"add_prefix":        starlark.NewBuiltin("add_prefix", methNoImplSeries("add_prefix")),
	"add_suffix":        starlark.NewBuiltin("add_suffix", methNoImplSeries("add_suffix")),
	"agg":               starlark.NewBuiltin("agg", methNoImplSeries("agg")),
	"aggregate":         starlark.NewBuiltin("aggregate", methNoImplSeries("aggregate")),
	"align":             starlark.NewBuiltin("align", methNoImplSeries("align")),
	"all":               starlark.NewBuiltin("all", methNoImplSeries("all")),
	"any":               starlark.NewBuiltin("any", methNoImplSeries("any")),
	"append":            starlark.NewBuiltin("append", methNoImplSeries("append")),
	"apply":             starlark.NewBuiltin("apply", methNoImplSeries("apply")),
	"argmax":            starlark.NewBuiltin("argmax", methNoImplSeries("argmax")),
	"argmin":            starlark.NewBuiltin("argmin", methNoImplSeries("argmin")),
	"argsort":           starlark.NewBuiltin("argsort", methNoImplSeries("argsort")),
	"asfreq":            starlark.NewBuiltin("asfreq", methNoImplSeries("asfreq")),
	"asof":              starlark.NewBuiltin("asof", methNoImplSeries("asof")),
	"astype":            starlark.NewBuiltin("astype", seriesAsType),
	"at_time":           starlark.NewBuiltin("at_time", methNoImplSeries("at_time")),
	"autocorr":          starlark.NewBuiltin("autocorr", methNoImplSeries("autocorr")),
	"backfill":          starlark.NewBuiltin("backfill", methNoImplSeries("backfill")),
	"between":           starlark.NewBuiltin("between", methNoImplSeries("between")),
	"between_time":      starlark.NewBuiltin("between_time", methNoImplSeries("between_time")),
	"bfill":             starlark.NewBuiltin("bfill", methNoImplSeries("bfill")),
	"bool":              starlark.NewBuiltin("bool", methNoImplSeries("bool")),
	"cat":               starlark.NewBuiltin("cat", methNoImplSeries("cat")),
	"clip":              starlark.NewBuiltin("clip", methNoImplSeries("clip")),
	"combine":           starlark.NewBuiltin("combine", methNoImplSeries("combine")),
	"combine_first":     starlark.NewBuiltin("combine_first", methNoImplSeries("combine_first")),
	"compare":           starlark.NewBuiltin("compare", methNoImplSeries("compare")),
	"convert_dtypes":    starlark.NewBuiltin("convert_dtypes", methNoImplSeries("convert_dtypes")),
	"copy":              starlark.NewBuiltin("copy", methNoImplSeries("copy")),
	"corr":              starlark.NewBuiltin("corr", methNoImplSeries("corr")),
	"count":             starlark.NewBuiltin("count", methNoImplSeries("count")),
	"cov":               starlark.NewBuiltin("cov", methNoImplSeries("cov")),
	"cummax":            starlark.NewBuiltin("cummax", methNoImplSeries("cummax")),
	"cummin":            starlark.NewBuiltin("cummin", methNoImplSeries("cummin")),
	"cumprod":           starlark.NewBuiltin("cumprod", methNoImplSeries("cumprod")),
	"cumsum":            starlark.NewBuiltin("cumsum", methNoImplSeries("cumsum")),
	"describe":          starlark.NewBuiltin("describe", methNoImplSeries("describe")),
	"diff":              starlark.NewBuiltin("diff", methNoImplSeries("diff")),
	"div":               starlark.NewBuiltin("div", methNoImplSeries("div")),
	"divide":            starlark.NewBuiltin("divide", methNoImplSeries("divide")),
	"divmod":            starlark.NewBuiltin("divmod", methNoImplSeries("divmod")),
	"dot":               starlark.NewBuiltin("dot", methNoImplSeries("dot")),
	"drop":              starlark.NewBuiltin("drop", methNoImplSeries("drop")),
	"drop_duplicates":   starlark.NewBuiltin("drop_duplicates", methNoImplSeries("drop_duplicates")),
	"droplevel":         starlark.NewBuiltin("droplevel", methNoImplSeries("droplevel")),
	"dropna":            starlark.NewBuiltin("dropna", methNoImplSeries("dropna")),
	"dt":                starlark.NewBuiltin("dt", methNoImplSeries("dt")),
	"duplicated":        starlark.NewBuiltin("duplicated", methNoImplSeries("duplicated")),
	"eq":                starlark.NewBuiltin("eq", methNoImplSeries("eq")),
	"equals":            starlark.NewBuiltin("equals", seriesEquals),
	"ewm":               starlark.NewBuiltin("ewm", methNoImplSeries("ewm")),
	"expanding":         starlark.NewBuiltin("expanding", methNoImplSeries("expanding")),
	"explode":           starlark.NewBuiltin("explode", methNoImplSeries("explode")),
	"factorize":         starlark.NewBuiltin("factorize", methNoImplSeries("factorize")),
	"ffill":             starlark.NewBuiltin("ffill", methNoImplSeries("ffill")),
	"fillna":            starlark.NewBuiltin("fillna", methNoImplSeries("fillna")),
	"filter":            starlark.NewBuiltin("filter", methNoImplSeries("filter")),
	"first":             starlark.NewBuiltin("first", methNoImplSeries("first")),
	"first_valid_index": starlark.NewBuiltin("first_valid_index", methNoImplSeries("first_valid_index")),
	"floordiv":          starlark.NewBuiltin("floordiv", methNoImplSeries("floordiv")),
	"ge":                starlark.NewBuiltin("ge", methNoImplSeries("ge")),
	"get":               starlark.NewBuiltin("get", seriesGet),
	"groupby":           starlark.NewBuiltin("groupby", methNoImplSeries("groupby")),
	"gt":                starlark.NewBuiltin("gt", methNoImplSeries("gt")),
	"head":              starlark.NewBuiltin("head", methNoImplSeries("head")),
	"hist":              starlark.NewBuiltin("hist", methNoImplSeries("hist")),
	"idxmax":            starlark.NewBuiltin("idxmax", methNoImplSeries("idxmax")),
	"idxmin":            starlark.NewBuiltin("idxmin", methNoImplSeries("idxmin")),
	"infer_objects":     starlark.NewBuiltin("infer_objects", methNoImplSeries("infer_objects")),
	"interpolate":       starlark.NewBuiltin("interpolate", methNoImplSeries("interpolate")),
	"isin":              starlark.NewBuiltin("isin", methNoImplSeries("isin")),
	"isna":              starlark.NewBuiltin("isna", methNoImplSeries("isna")),
	"isnull":            starlark.NewBuiltin("isnull", methNoImplSeries("isnull")),
	"item":              starlark.NewBuiltin("item", methNoImplSeries("item")),
	"items":             starlark.NewBuiltin("items", methNoImplSeries("items")),
	"iteritems":         starlark.NewBuiltin("iteritems", methNoImplSeries("iteritems")),
	"keys":              starlark.NewBuiltin("keys", methNoImplSeries("keys")),
	"kurt":              starlark.NewBuiltin("kurt", methNoImplSeries("kurt")),
	"kurtosis":          starlark.NewBuiltin("kurtosis", methNoImplSeries("kurtosis")),
	"last":              starlark.NewBuiltin("last", methNoImplSeries("last")),
	"last_valid_index":  starlark.NewBuiltin("last_valid_index", methNoImplSeries("last_valid_index")),
	"le":                starlark.NewBuiltin("le", methNoImplSeries("le")),
	"lt":                starlark.NewBuiltin("lt", methNoImplSeries("lt")),
	"mad":               starlark.NewBuiltin("mad", methNoImplSeries("mad")),
	"map":               starlark.NewBuiltin("map", methNoImplSeries("map")),
	"mask":              starlark.NewBuiltin("mask", methNoImplSeries("mask")),
	"max":               starlark.NewBuiltin("max", methNoImplSeries("max")),
	"mean":              starlark.NewBuiltin("mean", methNoImplSeries("mean")),
	"median":            starlark.NewBuiltin("median", methNoImplSeries("median")),
	"memory_usage":      starlark.NewBuiltin("memory_usage", methNoImplSeries("memory_usage")),
	"min":               starlark.NewBuiltin("min", methNoImplSeries("min")),
	"mod":               starlark.NewBuiltin("mod", methNoImplSeries("mod")),
	"mode":              starlark.NewBuiltin("mode", methNoImplSeries("mode")),
	"mul":               starlark.NewBuiltin("mul", methNoImplSeries("mul")),
	"multiply":          starlark.NewBuiltin("multiply", methNoImplSeries("multiply")),
	"ne":                starlark.NewBuiltin("ne", methNoImplSeries("ne")),
	"nlargest":          starlark.NewBuiltin("nlargest", methNoImplSeries("nlargest")),
	"notequals":         starlark.NewBuiltin("notequals", seriesNotEquals),
	"notna":             starlark.NewBuiltin("notna", methNoImplSeries("notna")),
	"notnull":           starlark.NewBuiltin("notnull", seriesNotNull),
	"nsmallest":         starlark.NewBuiltin("nsmallest", methNoImplSeries("nsmallest")),
	"nunique":           starlark.NewBuiltin("nunique", methNoImplSeries("nunique")),
	"pad":               starlark.NewBuiltin("pad", methNoImplSeries("pad")),
	"pct_change":        starlark.NewBuiltin("pct_change", methNoImplSeries("pct_change")),
	"pipe":              starlark.NewBuiltin("pipe", methNoImplSeries("pipe")),
	"plot":              starlark.NewBuiltin("plot", methNoImplSeries("plot")),
	"pop":               starlark.NewBuiltin("pop", methNoImplSeries("pop")),
	"pow":               starlark.NewBuiltin("pow", methNoImplSeries("pow")),
	"prod":              starlark.NewBuiltin("prod", methNoImplSeries("prod")),
	"product":           starlark.NewBuiltin("product", methNoImplSeries("product")),
	"quantile":          starlark.NewBuiltin("quantile", methNoImplSeries("quantile")),
	"radd":              starlark.NewBuiltin("radd", methNoImplSeries("radd")),
	"rank":              starlark.NewBuiltin("rank", methNoImplSeries("rank")),
	"ravel":             starlark.NewBuiltin("ravel", methNoImplSeries("ravel")),
	"rdiv":              starlark.NewBuiltin("rdiv", methNoImplSeries("rdiv")),
	"rdivmod":           starlark.NewBuiltin("rdivmod", methNoImplSeries("rdivmod")),
	"reindex":           starlark.NewBuiltin("reindex", methNoImplSeries("reindex")),
	"reindex_like":      starlark.NewBuiltin("reindex_like", methNoImplSeries("reindex_like")),
	"rename":            starlark.NewBuiltin("rename", methNoImplSeries("rename")),
	"rename_axis":       starlark.NewBuiltin("rename_axis", methNoImplSeries("rename_axis")),
	"reorder_levels":    starlark.NewBuiltin("reorder_levels", methNoImplSeries("reorder_levels")),
	"repeat":            starlark.NewBuiltin("repeat", methNoImplSeries("repeat")),
	"replace":           starlark.NewBuiltin("replace", methNoImplSeries("replace")),
	"resample":          starlark.NewBuiltin("resample", methNoImplSeries("resample")),
	"reset_index":       starlark.NewBuiltin("reset_index", seriesResetIndex),
	"rfloordiv":         starlark.NewBuiltin("rfloordiv", methNoImplSeries("rfloordiv")),
	"rmod":              starlark.NewBuiltin("rmod", methNoImplSeries("rmod")),
	"rmul":              starlark.NewBuiltin("rmul", methNoImplSeries("rmul")),
	"rolling":           starlark.NewBuiltin("rolling", methNoImplSeries("rolling")),
	"round":             starlark.NewBuiltin("round", methNoImplSeries("round")),
	"rpow":              starlark.NewBuiltin("rpow", methNoImplSeries("rpow")),
	"rsub":              starlark.NewBuiltin("rsub", methNoImplSeries("rsub")),
	"rtruediv":          starlark.NewBuiltin("rtruediv", methNoImplSeries("rtruediv")),
	"sample":            starlark.NewBuiltin("sample", methNoImplSeries("sample")),
	"searchsorted":      starlark.NewBuiltin("searchsorted", methNoImplSeries("searchsorted")),
	"sem":               starlark.NewBuiltin("sem", methNoImplSeries("sem")),
	"set_axis":          starlark.NewBuiltin("set_axis", methNoImplSeries("set_axis")),
	"set_flags":         starlark.NewBuiltin("set_flags", methNoImplSeries("set_flags")),
	"shift":             starlark.NewBuiltin("shift", adaptToSeriesFromDataframe("shift")),
	"skew":              starlark.NewBuiltin("skew", methNoImplSeries("skew")),
	"slice_shift":       starlark.NewBuiltin("slice_shift", methNoImplSeries("slice_shift")),
	"sort_index":        starlark.NewBuiltin("sort_index", methNoImplSeries("sort_index")),
	"sort_values":       starlark.NewBuiltin("sort_values", methNoImplSeries("sort_values")),
	"sparse":            starlark.NewBuiltin("sparse", methNoImplSeries("sparse")),
	"squeeze":           starlark.NewBuiltin("squeeze", methNoImplSeries("squeeze")),
	"std":               starlark.NewBuiltin("std", methNoImplSeries("std")),
	"str":               starlark.NewBuiltin("str", methNoImplSeries("str")),
	"sub":               starlark.NewBuiltin("sub", methNoImplSeries("sub")),
	"subtract":          starlark.NewBuiltin("subtract", methNoImplSeries("subtract")),
	"sum":               starlark.NewBuiltin("sum", methNoImplSeries("sum")),
	"swapaxes":          starlark.NewBuiltin("swapaxes", methNoImplSeries("swapaxes")),
	"swaplevel":         starlark.NewBuiltin("swaplevel", methNoImplSeries("swaplevel")),
	"tail":              starlark.NewBuiltin("tail", methNoImplSeries("tail")),
	"take":              starlark.NewBuiltin("take", methNoImplSeries("take")),
	"to_clipboard":      starlark.NewBuiltin("to_clipboard", methNoImplSeries("to_clipboard")),
	"to_csv":            starlark.NewBuiltin("to_csv", methNoImplSeries("to_csv")),
	"to_dict":           starlark.NewBuiltin("to_dict", methNoImplSeries("to_dict")),
	"to_excel":          starlark.NewBuiltin("to_excel", methNoImplSeries("to_excel")),
	"to_frame":          starlark.NewBuiltin("to_frame", seriesToFrame),
	"to_hdf":            starlark.NewBuiltin("to_hdf", methNoImplSeries("to_hdf")),
	"to_json":           starlark.NewBuiltin("to_json", methNoImplSeries("to_json")),
	"to_latex":          starlark.NewBuiltin("to_latex", methNoImplSeries("to_latex")),
	"to_list":           starlark.NewBuiltin("to_list", methNoImplSeries("to_list")),
	"to_markdown":       starlark.NewBuiltin("to_markdown", methNoImplSeries("to_markdown")),
	"to_numpy":          starlark.NewBuiltin("to_numpy", methNoImplSeries("to_numpy")),
	"to_period":         starlark.NewBuiltin("to_period", methNoImplSeries("to_period")),
	"to_pickle":         starlark.NewBuiltin("to_pickle", methNoImplSeries("to_pickle")),
	"to_sql":            starlark.NewBuiltin("to_sql", methNoImplSeries("to_sql")),
	"to_string":         starlark.NewBuiltin("to_string", methNoImplSeries("to_string")),
	"to_timestamp":      starlark.NewBuiltin("to_timestamp", methNoImplSeries("to_timestamp")),
	"to_xarray":         starlark.NewBuiltin("to_xarray", methNoImplSeries("to_xarray")),
	"tolist":            starlark.NewBuiltin("tolist", methNoImplSeries("tolist")),
	"transform":         starlark.NewBuiltin("transform", methNoImplSeries("transform")),
	"transpose":         starlark.NewBuiltin("transpose", methNoImplSeries("transpose")),
	"truediv":           starlark.NewBuiltin("truediv", methNoImplSeries("truediv")),
	"truncate":          starlark.NewBuiltin("truncate", methNoImplSeries("truncate")),
	"tshift":            starlark.NewBuiltin("tshift", methNoImplSeries("tshift")),
	"tz_convert":        starlark.NewBuiltin("tz_convert", methNoImplSeries("tz_convert")),
	"tz_localize":       starlark.NewBuiltin("tz_localize", methNoImplSeries("tz_localize")),
	"unique":            starlark.NewBuiltin("unique", seriesUnique),
	"unstack":           starlark.NewBuiltin("unstack", methNoImplSeries("unstack")),
	"update":            starlark.NewBuiltin("update", methNoImplSeries("update")),
	"value_counts":      starlark.NewBuiltin("value_counts", methNoImplSeries("value_counts")),
	"var":               starlark.NewBuiltin("var", methNoImplSeries("var")),
	"view":              starlark.NewBuiltin("view", methNoImplSeries("view")),
	"where":             starlark.NewBuiltin("where", methNoImplSeries("where")),
	"xs":                starlark.NewBuiltin("xs", methNoImplSeries("xs")),
}

func attrNoImplSeries(attrName string) seriesAttrImpl {
	return func(*Series) (starlark.Value, error) {
		return nil, fmt.Errorf("series.%s is not implemented. If you need this functionality to exist, file an issue at 'https://github.com/qri-io/starlib/issues' with the title 'series.%s needs implementation'. Please first search if an issue exists already", attrName, attrName)
	}
}

func methNoImplSeries(methodName string) starlarkMethod {
	return func(_ *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
		return nil, fmt.Errorf("series.%s is not implemented. If you need this functionality to exist, file an issue at 'https://github.com/qri-io/starlib/issues' with the title 'series.%s needs implementation'. Please first search if an issue exists already", methodName, methodName)
	}
}
