package dataframe

import (
	"go.starlark.net/starlark"
)

type seriesAttrImpl func(*Series) (starlark.Value, error)

var seriesAttributes = map[string]seriesAttrImpl{
	"T":                       attrNoImplSeries("T"),
	"array":                   attrNoImplSeries("array"),
	"at":                      attrNoImplSeries("at"),
	"attrs":                   attrNoImplSeries("attrs"),
	"axes":                    attrNoImplSeries("axes"),
	"dtype":                   attrNoImplSeries("dtype"),
	"dtypes":                  attrNoImplSeries("dtypes"),
	"flags":                   attrNoImplSeries("flags"),
	"hasnans":                 attrNoImplSeries("hasnans"),
	"iat":                     attrNoImplSeries("iat"),
	"iloc":                    attrNoImplSeries("iloc"),
	"index":                   attrNoImplSeries("index"),
	"is_monotonic":            attrNoImplSeries("is_monotonic"),
	"is_monotonic_decreasing": attrNoImplSeries("is_monotonic_decreasing"),
	"is_monotonic_increasing": attrNoImplSeries("is_monotonic_increasing"),
	"is_unique":               attrNoImplSeries("is_unique"),
	"loc":                     attrNoImplSeries("loc"),
	"name":                    attrNoImplSeries("name"),
	"nbytes":                  attrNoImplSeries("nbytes"),
	"ndim":                    attrNoImplSeries("ndim"),
	"shape":                   attrNoImplSeries("shape"),
	"size":                    attrNoImplSeries("size"),
	"values":                  attrNoImplSeries("values"),
}

var seriesMethods = map[string]*starlark.Builtin{
	"abs":               starlark.NewBuiltin("abs", methNoImpl("abs")),
	"add":               starlark.NewBuiltin("add", methNoImpl("add")),
	"add_prefix":        starlark.NewBuiltin("add_prefix", methNoImpl("add_prefix")),
	"add_suffix":        starlark.NewBuiltin("add_suffix", methNoImpl("add_suffix")),
	"agg":               starlark.NewBuiltin("agg", methNoImpl("agg")),
	"aggregate":         starlark.NewBuiltin("aggregate", methNoImpl("aggregate")),
	"align":             starlark.NewBuiltin("align", methNoImpl("align")),
	"all":               starlark.NewBuiltin("all", methNoImpl("all")),
	"any":               starlark.NewBuiltin("any", methNoImpl("any")),
	"append":            starlark.NewBuiltin("append", methNoImpl("append")),
	"apply":             starlark.NewBuiltin("apply", methNoImpl("apply")),
	"argmax":            starlark.NewBuiltin("argmax", methNoImpl("argmax")),
	"argmin":            starlark.NewBuiltin("argmin", methNoImpl("argmin")),
	"argsort":           starlark.NewBuiltin("argsort", methNoImpl("argsort")),
	"asfreq":            starlark.NewBuiltin("asfreq", methNoImpl("asfreq")),
	"asof":              starlark.NewBuiltin("asof", methNoImpl("asof")),
	"astype":            starlark.NewBuiltin("astype", seriesAsType),
	"at_time":           starlark.NewBuiltin("at_time", methNoImpl("at_time")),
	"autocorr":          starlark.NewBuiltin("autocorr", methNoImpl("autocorr")),
	"backfill":          starlark.NewBuiltin("backfill", methNoImpl("backfill")),
	"between":           starlark.NewBuiltin("between", methNoImpl("between")),
	"between_time":      starlark.NewBuiltin("between_time", methNoImpl("between_time")),
	"bfill":             starlark.NewBuiltin("bfill", methNoImpl("bfill")),
	"bool":              starlark.NewBuiltin("bool", methNoImpl("bool")),
	"cat":               starlark.NewBuiltin("cat", methNoImpl("cat")),
	"clip":              starlark.NewBuiltin("clip", methNoImpl("clip")),
	"combine":           starlark.NewBuiltin("combine", methNoImpl("combine")),
	"combine_first":     starlark.NewBuiltin("combine_first", methNoImpl("combine_first")),
	"compare":           starlark.NewBuiltin("compare", methNoImpl("compare")),
	"convert_dtypes":    starlark.NewBuiltin("convert_dtypes", methNoImpl("convert_dtypes")),
	"copy":              starlark.NewBuiltin("copy", methNoImpl("copy")),
	"corr":              starlark.NewBuiltin("corr", methNoImpl("corr")),
	"count":             starlark.NewBuiltin("count", methNoImpl("count")),
	"cov":               starlark.NewBuiltin("cov", methNoImpl("cov")),
	"cummax":            starlark.NewBuiltin("cummax", methNoImpl("cummax")),
	"cummin":            starlark.NewBuiltin("cummin", methNoImpl("cummin")),
	"cumprod":           starlark.NewBuiltin("cumprod", methNoImpl("cumprod")),
	"cumsum":            starlark.NewBuiltin("cumsum", methNoImpl("cumsum")),
	"describe":          starlark.NewBuiltin("describe", methNoImpl("describe")),
	"diff":              starlark.NewBuiltin("diff", methNoImpl("diff")),
	"div":               starlark.NewBuiltin("div", methNoImpl("div")),
	"divide":            starlark.NewBuiltin("divide", methNoImpl("divide")),
	"divmod":            starlark.NewBuiltin("divmod", methNoImpl("divmod")),
	"dot":               starlark.NewBuiltin("dot", methNoImpl("dot")),
	"drop":              starlark.NewBuiltin("drop", methNoImpl("drop")),
	"drop_duplicates":   starlark.NewBuiltin("drop_duplicates", methNoImpl("drop_duplicates")),
	"droplevel":         starlark.NewBuiltin("droplevel", methNoImpl("droplevel")),
	"dropna":            starlark.NewBuiltin("dropna", methNoImpl("dropna")),
	"dt":                starlark.NewBuiltin("dt", methNoImpl("dt")),
	"duplicated":        starlark.NewBuiltin("duplicated", methNoImpl("duplicated")),
	"eq":                starlark.NewBuiltin("eq", methNoImpl("eq")),
	"equals":            starlark.NewBuiltin("equals", seriesEquals),
	"ewm":               starlark.NewBuiltin("ewm", methNoImpl("ewm")),
	"expanding":         starlark.NewBuiltin("expanding", methNoImpl("expanding")),
	"explode":           starlark.NewBuiltin("explode", methNoImpl("explode")),
	"factorize":         starlark.NewBuiltin("factorize", methNoImpl("factorize")),
	"ffill":             starlark.NewBuiltin("ffill", methNoImpl("ffill")),
	"fillna":            starlark.NewBuiltin("fillna", methNoImpl("fillna")),
	"filter":            starlark.NewBuiltin("filter", methNoImpl("filter")),
	"first":             starlark.NewBuiltin("first", methNoImpl("first")),
	"first_valid_index": starlark.NewBuiltin("first_valid_index", methNoImpl("first_valid_index")),
	"floordiv":          starlark.NewBuiltin("floordiv", methNoImpl("floordiv")),
	"ge":                starlark.NewBuiltin("ge", methNoImpl("ge")),
	"get":               starlark.NewBuiltin("get", seriesGet),
	"groupby":           starlark.NewBuiltin("groupby", methNoImpl("groupby")),
	"gt":                starlark.NewBuiltin("gt", methNoImpl("gt")),
	"head":              starlark.NewBuiltin("head", methNoImpl("head")),
	"hist":              starlark.NewBuiltin("hist", methNoImpl("hist")),
	"idxmax":            starlark.NewBuiltin("idxmax", methNoImpl("idxmax")),
	"idxmin":            starlark.NewBuiltin("idxmin", methNoImpl("idxmin")),
	"infer_objects":     starlark.NewBuiltin("infer_objects", methNoImpl("infer_objects")),
	"interpolate":       starlark.NewBuiltin("interpolate", methNoImpl("interpolate")),
	"isin":              starlark.NewBuiltin("isin", methNoImpl("isin")),
	"isna":              starlark.NewBuiltin("isna", methNoImpl("isna")),
	"isnull":            starlark.NewBuiltin("isnull", methNoImpl("isnull")),
	"item":              starlark.NewBuiltin("item", methNoImpl("item")),
	"items":             starlark.NewBuiltin("items", methNoImpl("items")),
	"iteritems":         starlark.NewBuiltin("iteritems", methNoImpl("iteritems")),
	"keys":              starlark.NewBuiltin("keys", methNoImpl("keys")),
	"kurt":              starlark.NewBuiltin("kurt", methNoImpl("kurt")),
	"kurtosis":          starlark.NewBuiltin("kurtosis", methNoImpl("kurtosis")),
	"last":              starlark.NewBuiltin("last", methNoImpl("last")),
	"last_valid_index":  starlark.NewBuiltin("last_valid_index", methNoImpl("last_valid_index")),
	"le":                starlark.NewBuiltin("le", methNoImpl("le")),
	"lt":                starlark.NewBuiltin("lt", methNoImpl("lt")),
	"mad":               starlark.NewBuiltin("mad", methNoImpl("mad")),
	"map":               starlark.NewBuiltin("map", methNoImpl("map")),
	"mask":              starlark.NewBuiltin("mask", methNoImpl("mask")),
	"max":               starlark.NewBuiltin("max", methNoImpl("max")),
	"mean":              starlark.NewBuiltin("mean", methNoImpl("mean")),
	"median":            starlark.NewBuiltin("median", methNoImpl("median")),
	"memory_usage":      starlark.NewBuiltin("memory_usage", methNoImpl("memory_usage")),
	"min":               starlark.NewBuiltin("min", methNoImpl("min")),
	"mod":               starlark.NewBuiltin("mod", methNoImpl("mod")),
	"mode":              starlark.NewBuiltin("mode", methNoImpl("mode")),
	"mul":               starlark.NewBuiltin("mul", methNoImpl("mul")),
	"multiply":          starlark.NewBuiltin("multiply", methNoImpl("multiply")),
	"ne":                starlark.NewBuiltin("ne", methNoImpl("ne")),
	"nlargest":          starlark.NewBuiltin("nlargest", methNoImpl("nlargest")),
	"notequals":         starlark.NewBuiltin("notequals", seriesNotEquals),
	"notna":             starlark.NewBuiltin("notna", methNoImpl("notna")),
	"notnull":           starlark.NewBuiltin("notnull", seriesNotNull),
	"nsmallest":         starlark.NewBuiltin("nsmallest", methNoImpl("nsmallest")),
	"nunique":           starlark.NewBuiltin("nunique", methNoImpl("nunique")),
	"pad":               starlark.NewBuiltin("pad", methNoImpl("pad")),
	"pct_change":        starlark.NewBuiltin("pct_change", methNoImpl("pct_change")),
	"pipe":              starlark.NewBuiltin("pipe", methNoImpl("pipe")),
	"plot":              starlark.NewBuiltin("plot", methNoImpl("plot")),
	"pop":               starlark.NewBuiltin("pop", methNoImpl("pop")),
	"pow":               starlark.NewBuiltin("pow", methNoImpl("pow")),
	"prod":              starlark.NewBuiltin("prod", methNoImpl("prod")),
	"product":           starlark.NewBuiltin("product", methNoImpl("product")),
	"quantile":          starlark.NewBuiltin("quantile", methNoImpl("quantile")),
	"radd":              starlark.NewBuiltin("radd", methNoImpl("radd")),
	"rank":              starlark.NewBuiltin("rank", methNoImpl("rank")),
	"ravel":             starlark.NewBuiltin("ravel", methNoImpl("ravel")),
	"rdiv":              starlark.NewBuiltin("rdiv", methNoImpl("rdiv")),
	"rdivmod":           starlark.NewBuiltin("rdivmod", methNoImpl("rdivmod")),
	"reindex":           starlark.NewBuiltin("reindex", methNoImpl("reindex")),
	"reindex_like":      starlark.NewBuiltin("reindex_like", methNoImpl("reindex_like")),
	"rename":            starlark.NewBuiltin("rename", methNoImpl("rename")),
	"rename_axis":       starlark.NewBuiltin("rename_axis", methNoImpl("rename_axis")),
	"reorder_levels":    starlark.NewBuiltin("reorder_levels", methNoImpl("reorder_levels")),
	"repeat":            starlark.NewBuiltin("repeat", methNoImpl("repeat")),
	"replace":           starlark.NewBuiltin("replace", methNoImpl("replace")),
	"resample":          starlark.NewBuiltin("resample", methNoImpl("resample")),
	"reset_index":       starlark.NewBuiltin("reset_index", seriesResetIndex),
	"rfloordiv":         starlark.NewBuiltin("rfloordiv", methNoImpl("rfloordiv")),
	"rmod":              starlark.NewBuiltin("rmod", methNoImpl("rmod")),
	"rmul":              starlark.NewBuiltin("rmul", methNoImpl("rmul")),
	"rolling":           starlark.NewBuiltin("rolling", methNoImpl("rolling")),
	"round":             starlark.NewBuiltin("round", methNoImpl("round")),
	"rpow":              starlark.NewBuiltin("rpow", methNoImpl("rpow")),
	"rsub":              starlark.NewBuiltin("rsub", methNoImpl("rsub")),
	"rtruediv":          starlark.NewBuiltin("rtruediv", methNoImpl("rtruediv")),
	"sample":            starlark.NewBuiltin("sample", methNoImpl("sample")),
	"searchsorted":      starlark.NewBuiltin("searchsorted", methNoImpl("searchsorted")),
	"sem":               starlark.NewBuiltin("sem", methNoImpl("sem")),
	"set_axis":          starlark.NewBuiltin("set_axis", methNoImpl("set_axis")),
	"set_flags":         starlark.NewBuiltin("set_flags", methNoImpl("set_flags")),
	"shift":             starlark.NewBuiltin("shift", methNoImpl("shift")),
	"skew":              starlark.NewBuiltin("skew", methNoImpl("skew")),
	"slice_shift":       starlark.NewBuiltin("slice_shift", methNoImpl("slice_shift")),
	"sort_index":        starlark.NewBuiltin("sort_index", methNoImpl("sort_index")),
	"sort_values":       starlark.NewBuiltin("sort_values", methNoImpl("sort_values")),
	"sparse":            starlark.NewBuiltin("sparse", methNoImpl("sparse")),
	"squeeze":           starlark.NewBuiltin("squeeze", methNoImpl("squeeze")),
	"std":               starlark.NewBuiltin("std", methNoImpl("std")),
	"str":               starlark.NewBuiltin("str", methNoImpl("str")),
	"sub":               starlark.NewBuiltin("sub", methNoImpl("sub")),
	"subtract":          starlark.NewBuiltin("subtract", methNoImpl("subtract")),
	"sum":               starlark.NewBuiltin("sum", methNoImpl("sum")),
	"swapaxes":          starlark.NewBuiltin("swapaxes", methNoImpl("swapaxes")),
	"swaplevel":         starlark.NewBuiltin("swaplevel", methNoImpl("swaplevel")),
	"tail":              starlark.NewBuiltin("tail", methNoImpl("tail")),
	"take":              starlark.NewBuiltin("take", methNoImpl("take")),
	"to_clipboard":      starlark.NewBuiltin("to_clipboard", methNoImpl("to_clipboard")),
	"to_csv":            starlark.NewBuiltin("to_csv", methNoImpl("to_csv")),
	"to_dict":           starlark.NewBuiltin("to_dict", methNoImpl("to_dict")),
	"to_excel":          starlark.NewBuiltin("to_excel", methNoImpl("to_excel")),
	"to_frame":          starlark.NewBuiltin("to_frame", seriesToFrame),
	"to_hdf":            starlark.NewBuiltin("to_hdf", methNoImpl("to_hdf")),
	"to_json":           starlark.NewBuiltin("to_json", methNoImpl("to_json")),
	"to_latex":          starlark.NewBuiltin("to_latex", methNoImpl("to_latex")),
	"to_list":           starlark.NewBuiltin("to_list", methNoImpl("to_list")),
	"to_markdown":       starlark.NewBuiltin("to_markdown", methNoImpl("to_markdown")),
	"to_numpy":          starlark.NewBuiltin("to_numpy", methNoImpl("to_numpy")),
	"to_period":         starlark.NewBuiltin("to_period", methNoImpl("to_period")),
	"to_pickle":         starlark.NewBuiltin("to_pickle", methNoImpl("to_pickle")),
	"to_sql":            starlark.NewBuiltin("to_sql", methNoImpl("to_sql")),
	"to_string":         starlark.NewBuiltin("to_string", methNoImpl("to_string")),
	"to_timestamp":      starlark.NewBuiltin("to_timestamp", methNoImpl("to_timestamp")),
	"to_xarray":         starlark.NewBuiltin("to_xarray", methNoImpl("to_xarray")),
	"tolist":            starlark.NewBuiltin("tolist", methNoImpl("tolist")),
	"transform":         starlark.NewBuiltin("transform", methNoImpl("transform")),
	"transpose":         starlark.NewBuiltin("transpose", methNoImpl("transpose")),
	"truediv":           starlark.NewBuiltin("truediv", methNoImpl("truediv")),
	"truncate":          starlark.NewBuiltin("truncate", methNoImpl("truncate")),
	"tshift":            starlark.NewBuiltin("tshift", methNoImpl("tshift")),
	"tz_convert":        starlark.NewBuiltin("tz_convert", methNoImpl("tz_convert")),
	"tz_localize":       starlark.NewBuiltin("tz_localize", methNoImpl("tz_localize")),
	"unique":            starlark.NewBuiltin("unique", seriesUnique),
	"unstack":           starlark.NewBuiltin("unstack", methNoImpl("unstack")),
	"update":            starlark.NewBuiltin("update", methNoImpl("update")),
	"value_counts":      starlark.NewBuiltin("value_counts", methNoImpl("value_counts")),
	"var":               starlark.NewBuiltin("var", methNoImpl("var")),
	"view":              starlark.NewBuiltin("view", methNoImpl("view")),
	"where":             starlark.NewBuiltin("where", methNoImpl("where")),
	"xs":                starlark.NewBuiltin("xs", methNoImpl("xs")),
}
